### PR TITLE
COL-1283, create db table to track 'events' a la MixPanel

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/COL-1283
* I chose not to include foreign key constraints. This is an audit log and should not 'cascade on delete' or similar.
* The not-null columns: event_name, event_metadata, canvas_domain

### CODE REVIEW

**Comment by paulkerschen** [comment]
Looks good from my end, @johncrossman, but @sandeepmjay might want to review- I think he was hoping for a generated UUID string.

**Comment by johncrossman** [comment]
Thanks @paulkerschen  I've amended to include `uuid` (with type uuid). I considered it as primary-key but, considering [the pitfalls](https://tomharrisonjr.com/uuid-or-guid-as-primary-keys-be-careful-7b2aa3dcb439), I decided against.  cc: @sandeepmjay

**Comment by johncrossman** [comment]
@sandeepmjay what should change, if anything, in this db table def?

**Comment by sandeepmjay** [comment]
@johncrossman @paulkerschen 
Mixpanel event feed uses only 2 keys {event: string, properties:object}. Storing mixpanel event properties as event.metadata is a good idea. It would make it easier to re-stream events back to mixpanel if researchers got with it as a tool of choice.   User metadata seems unnecessary if we have a user_id. 

I recommend parsing any object_ids(assets, comments, whiteboards) that we come across in the properties and adding them as columns for easier filtering on the event log table.

**Comment by johncrossman** [comment]
@sandeepmjay @paulkerschen Amendment in, Travis green. I removed `user_metadata` and added nullable columns: `asset_id`, `comment_id`, `whiteboard_id`, `whiteboard_element_uid`. (The latter `_uid` suffix matches naming in whiteboard_elements table.

**Comment by sandeepmjay** [comment]
Now, that looks like a mixpanel killer.

**Pull request merged**
