### PR TITLE
[QA] COL-1343, replace paulkerschen/caliper-js with ets-berkeley-edu/caliper-js

### PR DESCRIPTION
**Pull request by johncrossman**
https://jira.ets.berkeley.edu/jira/browse/COL-1343

Master PR: https://github.com/ets-berkeley-edu/suitec/pull/739

### CODE REVIEW

**Comment by paulkerschen** [comment]
@johncrossman @sandeepmjay FWIW, IMS has finally reversed their private-repo policy, so it should be possible to point directly to https://github.com/IMSGlobal/caliper-js if desired.

**Comment by johncrossman** [comment]
@paulkerschen –  I was prompted for ssh key/auth when using IMSGlobal ref, `git@github.com:IMSGlobal/caliper-js.git#master`, earlier. I was skeptical of it working on Travis and EC2.  With cloud-lrs, @sandeepmjay is using IMSGlobal git ref but relies on https://github.com/ets-berkeley-edu/cloud-lrs/blob/master/.ebextensions/01_private_git_setup.config; he was unable to get `npm install` to work on Travis. I welcome your insight.

**Comment by paulkerschen** [comment]
@johncrossman I see - sounds like something’s not working as advertised. This should do just fine so long as IMS isn’t publishing to noon.

**Comment by raydavis** [comment]
@johncrossman I usually avoid ssh prompts by using "https://github.com/"-style references instead of "git@". Did you get a chance to try that?

**Comment by johncrossman** [comment]
@raydavis I did. I'll experiment a bit more today.

**Pull request merged**
