### PR TITLE
NOJIRA, our boilerplate is vaulted to 2017

### PR DESCRIPTION
**Pull request by johncrossman**
'master' will be deployed in 2017, I believe.

### CODE REVIEW

**Comment by paulkerschen** [comment]
@johncrossman I regret to note that all the css and js files in the codebase have "Copyright ©2016" at top. Fix here or separate issue?

**Comment by johncrossman** [comment]
@paulkerschen Yes, I was/am aware. Oh golly, I'll just update all files now.

**Comment by johncrossman** [comment]
By popular demand... 173 modified files.  cc: @paulkerschen

**Comment by paulkerschen** [comment]
I feel so contemporary!

**Pull request merged**
